name: github actions test
on:
  pull_request:
    branches:
      - develop
    types: 
      - opened
      - synchronize

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
