name: github actions test
on:
  pull_request:
    branches:
      - develop
    types: 
      - opened
      - synchronize
    paths:
      - 'dags/**'
      - '.github/workflows/**'

jobs:
  no_merge:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged

  if_merged:
    if: github.event.pull_request.merged == true
    needs: [no_merge]
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
        
