name: Prod

on:
  # releaseタグがmasterにpushされたタイミングでトリガ
  # example: git push origin v1.x.x 
  push:
    branches:
      - main
    tags:
      - 'v*'
  release:
    types:
      - created

jobs:
  no_merge:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo hoge hoge


