name: github actions stg test
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  stg:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged